source 'https://rubygems.org'

gem 'smashing'
gem 'ruby_dlrnapi', :git => 'https://github.com/halcyondude/ruby_dlrnapi.git'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'